config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

  authenticated do
    root to: "discussions#index"
  end

  resources :discussions do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end

    resources :notifications, only: :create, module: :discussions
  end

  resources :notifications, only: :index do
    collection do
      post '/mark_as_read', to: "notifications#read_all", as: :read
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  delegate :name, prefix: :category, to: :category, allow_nil: true

  validates :title, presence: true

  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  has_many :discussion_subscriptions, dependent: :destroy
  has_many :optin_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optin }) },
    through: :discussion_subscriptions,
    source: :user
  has_many :optout_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optout }) },
    through: :discussion_subscriptions,
    source: :user

  accepts_nested_attributes_for :posts

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to "discussions" }
  after_update_commit -> { broadcast_replace_to "discussions" }
  after_destroy_commit -> { broadcast_remove_to "discussions" }

  def to_param
    "#{id}-#{title.downcase.to_s[0...100]}".parameterize
  end

  def subscribed_users
    (users + optin_subscribers).uniq - optout_subscribers
  end

  def subscription_for(user)
    return nil if user.nil?
    discussion_subscriptions.find_by(user_id: user.id)
  end

  def toggle_subscription(user)
    if subscription = subscription_for(user)
      subscription.toggle!
    elsif posts.where(user_id: user.id).any?
      discussion_subscriptions.create(user: user, subscription_type: "optout")
    else
      discussion_subscriptions.create(user: user, subscription_type: "optin")
    end
  end

  def subscribed?(user)
    return false if user.nil?

    if subscription = subscription_for(user)
      subscription.subscription_type == "optin"
    else
      posts.where(user_id: user.id).any?
    end
  end

  def subscribed_reason(user)
    return "You're not receiving notifications from this thread, please subscribe to receive them" if user.nil?

    if subscription = subscription_for(user)
      if subscription.subscription_type == "optout"
        "You're ignoring this thread."
      elsif subscription.subscription_type == "optin"
        "You're receiving notifications because you've subscribed to this football discussion."
      end
    elsif posts.where(user_id: user.id).any?
      "You're receiving notifications because you've posted in this football discussion."
    else
      "You're not receiving notifications from this football discusssion"
    end
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category

    def index
      @pagy, @discussions = pagy(@category.discussions.order(updated_at: :desc))
      render 'discussions/index'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/notifications_controller.rb
module Discussions
  class NotificationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion

    def create
      @discussion.toggle_subscription(Current.user)
      redirect_to @discussion
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    include Pagy::Backend
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: [:show, :edit, :update, :destroy]


    def show

    end

    def edit

    end


    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: "Post updated" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          send_post_notification!(@post)

          @pagy, @posts = pagy(@discussion.posts.order(created_at: :desc), items: 5)
          format.html { redirect_to discussion_path(@discussion, page: @pagy.last), notice: "Post created" }
          format.turbo_stream
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream { }
        format.html { redirect_to @post.discussion, notice: "Post has been deleted" }
      end
    end

    private

    def send_post_notification!(post)
      post_subscribers = post.discussion.subscribed_users - [post.user]
      NewPostNotification.with(post: post).deliver_later(post_subscribers)
    end

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end


    def post_params
      params.require(:post).permit(:content)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :destroy, :update]

  def index
    @pagy, @discussions = pagy(Discussion.includes(:category), items: 5)
  end

  def show
    @discussion = Discussion.find(params[:id])

    @pagy, @posts = pagy(@discussion.posts.includes(:user, :rich_text_content).order(created_at: :asc), items: 5)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "A Discussion has been created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        DiscussionBroadcaster.new(@discussion).broadcast!
        format.html { redirect_to @discussion, notice: "This discussion has been updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: "This discussion has now been removed"
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :category_id, :closed, posts_attributes: :content)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>" class="mb-2">
  <h3><%= link_to discussion.title, discussion %></h3>
    Closed: <%= discussion.closed %>
    Posted in: <%= discussion.category_name %> | Posts: <%= discussion.posts_count %>
  <div>
    <%= link_to "Edit", edit_discussion_path(discussion) %>
    <%= link_to "Delete", discussion_path(discussion), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this discussion? This cannot be undone" } %>
  </div>
</div>

app/views/discussions/_discussion_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do %>
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <h2><%= discussion.title %></h2>
    </div>

    <% if discussion.closed %>
      <span class="badge rounded-pill text-danger">Closed</span>
    <% end %>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion) %>
      <%= link_to "Delete", discussion_path(discussion), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this discussion? This cannot be undone" } %>
    </div>
  </div>
<% end %>

app/views/discussions/_form.html.erb
<%= simple_form_for @discussion do |f| %>
  <%= f.input :title, label: 'Please enter a discussion title', error: 'Title is mandatory, please specify one' %>

  <div class="mb-2">
    <%= f.label :category_id, "Choose a category..." %>
    <%= f.collection_select :category_id, Category.sorted, :id, :name,
    { include_blank: "Pick a category..."}, { autofocus: false, class: "form-control" } %>
  </div>

  <div class="mb-2">
    <%= f.label :closed, class: "form-label" %>
    <%= f.check_box :closed %>
  </div>

  <% if @discussion.new_record? %>
    <%= f.simple_fields_for :posts do |p| %>
      <div class="mb-2">
        <%= p.rich_text_area :content, placeholder: "Talk football..." %>
      </div>
    <% end %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/discussions/edit.html.erb
<h2> Edit this Discussion</h2>
<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render("form", discussion: :@discussion) %>
  <%= link_to "Cancel", @discussion %>
<% end %>

app/views/discussions/index.html.erb
<% if @category.present? %>
  <%= turbo_stream_from @category %>
<% else %>
  <%= turbo_stream_from 'discussions' %>
<% end %>

<div class="d-flex justify-content-between align-items-center">
  <h1>Active Discussions</h1>
  <%= link_to "Create a Discussion", new_discussion_path, class: "btn btn-secondary" %>
</div>


<div class="row mt-4">
 <div class="col-3">
    <%= turbo_stream_from 'categories' %>
    <h3>Categories</h3>
    <div id="categories">
      <%= render(partial: "categories/category", collection: Category.sorted) %>
    </div>
  </div>

    <div class="col">
      <% if @category %>
        <h4>Viewing discussions in <%= @category.name %></h4>
      <% end %>
      <% if params[:page].blank? || params[:page].eql?('1') %>
        <div id="discussions"></div>
      <% end %>
      <%= render partial: "discussions/discussion", collection: @discussions %>

      <hr class="mb-4">

      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<h1>New Football Discussion</h1>

<%= render("form", discussion: :@discussion) %>

app/views/discussions/show.html.erb
<%= link_to "Back to Discussions", discussions_path, class: "btn btn-secondary" %>

<%= turbo_stream_from @discussion %>

<%= render(partial: "discussions/discussion_header", locals: { discussion: @discussion }) %>

<div class="mt-4">
  <%= render partial: "discussions/posts/post", collection: @posts %>
  <% if @pagy.page == @pagy.last %>
    <div id="posts"></div>
  <% end %>
</div>

<hr class="my-4">


<%== pagy_bootstrap_nav(@pagy) %>


<hr class="my-4">

<%= turbo_frame_tag "discussion_notification_status" do %>
  <%= render("discussions/notifications/status", discussion: @discussion, user: Current.user) %>
<% end %>

<hr class="my-4">

<div id="<%= dom_id(@new_post) %>">
  <%= render("discussions/posts/form", post: @new_post, redirect: @pagy.page != @pagy.last) %>
</div>