config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

  authenticated do
    root to: "discussions#index"
  end

  resources :discussions do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end

    resources :notifications, only: :create, module: :discussions
  end

  resources :notifications, only: :index do
    collection do
      post '/mark_as_read', to: "notifications#read_all", as: :read
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  delegate :name, prefix: :category, to: :category, allow_nil: true

  validates :title, presence: true

  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  has_many :discussion_subscriptions, dependent: :destroy
  has_many :optin_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optin }) },
    through: :discussion_subscriptions,
    source: :user
  has_many :optout_subscribers, -> { where(discussion_subscriptions: { subscription_type: :optout }) },
    through: :discussion_subscriptions,
    source: :user

  accepts_nested_attributes_for :posts

  broadcasts_to :category, inserts_by: :prepend

  after_create_commit -> { broadcast_prepend_to "discussions" }
  after_update_commit -> { broadcast_replace_to "discussions" }
  after_destroy_commit -> { broadcast_remove_to "discussions" }

  def to_param
    "#{id}-#{title.downcase.to_s[0...100]}".parameterize
  end

  def subscribed_users
    (users + optin_subscribers).uniq - optout_subscribers
  end

  def subscription_for(user)
    return nil if user.nil?
    discussion_subscriptions.find_by(user_id: user.id)
  end

  def toggle_subscription(user)
    if subscription = subscription_for(user)
      subscription.toggle!
    elsif posts.where(user_id: user.id).any?
      discussion_subscriptions.create(user: user, subscription_type: "optout")
    else
      discussion_subscriptions.create(user: user, subscription_type: "optin")
    end
  end

  def subscribed?(user)
    return false if user.nil?

    if subscription = subscription_for(user)
      subscription.subscription_type == "optin"
    else
      posts.where(user_id: user.id).any?
    end
  end

  def subscribed_reason(user)
    return "You're not receiving notifications from this thread, please subscribe to receive them" if user.nil?

    if subscription = subscription_for(user)
      if subscription.subscription_type == "optout"
        "You're ignoring this thread."
      elsif subscription.subscription_type == "optin"
        "You're receiving notifications because you've subscribed to this football discussion."
      end
    elsif posts.where(user_id: user.id).any?
      "You're receiving notifications because you've posted in this football discussion."
    else
      "You're not receiving notifications from this football discusssion"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :discussion, counter_cache: true, touch: true
  belongs_to :team, optional: true
  has_rich_text :content

  has_noticed_notifications


  validates :content, presence: true

  after_create_commit -> { broadcast_append_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_update_commit -> { broadcast_replace_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_destroy_commit -> { broadcast_remove_to discussion }


  def likes_count
    likes.count
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
  class DiscussionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category

    def index
      @pagy, @discussions = pagy(@category.discussions.order(updated_at: :desc))
      render 'discussions/index'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/discussions/notifications_controller.rb
module Discussions
  class NotificationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion

    def create
      @discussion.toggle_subscription(Current.user)
      redirect_to @discussion
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end
  end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    include Pagy::Backend
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: [:show, :edit, :update, :destroy]


    def show

    end

    def edit

    end


    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: "Post updated" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          send_post_notification!(@post)

          @pagy, @posts = pagy(@discussion.posts.order(created_at: :desc), items: 5)
          format.html { redirect_to discussion_path(@discussion, page: @pagy.last), notice: "Post created" }
          format.turbo_stream
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream { }
        format.html { redirect_to @post.discussion, notice: "Post has been deleted" }
      end
    end

    private

    def send_post_notification!(post)
      post_subscribers = post.discussion.subscribed_users - [post.user]
      NewPostNotification.with(post: post).deliver_later(post_subscribers)
    end

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end


    def post_params
      params.require(:post).permit(:content)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :destroy, :update]

  def index
    @pagy, @discussions = pagy(Discussion.includes(:category), items: 5)
  end

  def show
    @discussion = Discussion.find(params[:id])

    @pagy, @posts = pagy(@discussion.posts.includes(:user, :rich_text_content).order(created_at: :asc), items: 5)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "A Discussion has been created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        DiscussionBroadcaster.new(@discussion).broadcast!
        format.html { redirect_to @discussion, notice: "This discussion has been updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: "This discussion has now been removed"
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :category_id, :closed, posts_attributes: :content)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/discussions/posts/_form.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_form", target: "_top"  do %>
  <% if post.discussion.closed? && post.new_record? %>
    <div class="alert alert-secondary fw-bold" role="alert">
      This discussion is currently locked and new posts cannot be posted.
    </div>
  <% else %>
    <%= simple_form_for([post.discussion, post]) do |f| %>
      <%= f.error_notification %>

    <div class="mb-3">
      <%= f.input :content, as: :rich_text_area, input_html: { placeholder: "Add your post", autofocus: true }, label: false %>
    </div>

      <% if local_assigns[:redirect] %>
        <%= f.hidden_field :redirect, value: true %>
      <% end %>

    <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="card my-2">
    <div class="card-body">
      <%= render(partial: "discussions/posts/posts_header", locals: { post: post }) %>
      <%= post.content %>
    </div>

    <% if action_name.nil? %>
       <%= turbo_frame_tag "post_actions", src: discussion_post_path(post.discussion, post) do %>
         <div class="card-footer">
       <% end %>
    <% else %>
      <%= turbo_frame_tag "post_actions" do %>
        <% if Current.user == post.user || Current.user.admin? %>
          <div class="card-footer mt-2">
            <%= link_to "Edit", edit_discussion_post_path(post.discussion, post), data: { turbo_frame: dom_id(post) } %> |
            <%= link_to "Delete", discussion_post_path(post.discussion, post),
                    data: {
                      turbo_method: :delete,
                      turbo_frame: dom_id(post),
                      turbo_confirm: "Are you sure you want to delete this post?"
                    } %>    </div>
            </div>
          <% end %>
        <% end %>
      <% end %>#
    </div>
<% end %>

app/views/discussions/posts/_posts_header.html.erb
<h2 class="card-title"><%= post.user %></h2>
<h4 class="card-subtitle mb-2 text-muted border-bottom pb-2">Posted on: <%= post.created_at %></h4>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace "new_post_form" do %>
  <%= render partial: "discussions/posts/form", formats: :html, locals: { post: @post, redirect: true } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<h1>Edit post</h1>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class="card my-4">
    <div class="card-body">
      <%= render(partial: "discussions/posts/posts_header", locals: { post: @post }) %>
      <%= render("form", post: @post) %>
      <%= link_to 'Back', discussion_post_path(@post.discussion, @post) %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/show.html.erb
<%= render partial: "discussions/posts/post", locals: { post: @post } %>