config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

  authenticated do
    root to: "discussions#index"
  end

  resources :discussions do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end

    resources :notifications, only: :create, module: :discussions
  end

  resources :notifications, only: :index do
    collection do
      post '/mark_as_read', to: "notifications#read_all", as: :read
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/views/shared/_footer.html.erb
<div class="footer">
  <footer class="bg-light">
    <h2>Placeholder Footer</h2>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand">Football Forum 1</a>
    <ul class="navbar-nav mb-4 mb-lg-0">
      <%= link_to "Discussions", discussions_path, class: "nav-item nav-link" %>
      <%= link_to "Categories", categories_path, class: "nav-item nav-link" %>
      <%= link_to "Notifications", notifications_path, class: "nav-item nav-link" %>
    </ul>
    <ul class="navbar-nav mb-2 mb-lg-2">
      <% if user_signed_in? %>
        <%= link_to Current.user.email, edit_user_registration_path, method: :edit %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </ul>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>